### ISSUE TITLE
Server menu bug

### ISSUE THREAD

**Issue by 3ijtKwijt** [BeardDesign1/Material-design-theme#17]
The new update caused an issue with the other style that I am using (Titlebar)
The issue is with the server menu => http://prntscr.com/enxa85

Hope this can be fixed! :)

**Comment by BeardDesign1** [comment]
May I ask, which themes/plugins do you have on?

**Comment by 3ijtKwijt** [comment]
Styles:
• Material Theme for Discord (by you)
• Titlebar (also by you)

Plugins: (I used to use these, but even without them, it's still giving the issue)
• OwnerTags
• Latency Display

**Comment by Kugane** [comment]
:O there is a report for this.
having the same problem, http://imgur.com/a/SpNAv

Just using your Material Theme + Titelbar+ SmallMembersTab

**Comment by BeardDesign1** [comment]
Yeah sorry for not addressing the issue here, there's not really a way for now to make those two themes (titlebar+material theme) work together well since the 2.0 material theme update, I'll try to find a way to make it work in the future but now I'm focused on preparing the new user settings(currently in discord canary) for when the public release comes out. I'll update you on this asap.

**Comment by BeardDesign1** [comment]
I fixed this a while ago, update the titlebar theme ;)
