### ISSUE TITLE
Please add the ability to revert back to the Red Dot for notifications

### ISSUE THREAD

**Issue by KuroThing** [BeardDesign1/Material-design-theme#19]
I would like the ability to revert to the Red Dot as the notification icon. On my screen, for whatever reason the circle looks horrible. 

![image](https://cloud.githubusercontent.com/assets/18753877/24529137/b7ca7ad2-15f5-11e7-95e9-33054e5966f4.png)

And just doesn't look decent against all server icons (Especially those with transparency), while the Red Dot suited it far better. This is my opinion, and i would like it if i could just use some sort of Custom CSS to revert back to the old Red Dot, otherwise i'll need to revert back to v1.9.5 and i would rather continue to receive updates :(

**Comment by LambArchie** [comment]
I also feel the red dot worked better than the ring for me

**Comment by KuroThing** [comment]
So why was this closed?

**Comment by ghost** [comment]
If you wanna make your own version, he doesn't actually own the rights to this code, none of it is proprietary and as it's uploaded here, it's protected by the GNU GPL license, which allows and encourages free distribution of code. ;)

**Comment by BeardDesign1** [comment]
@TheCNixon ok, so let me repost your comment because you seem to have edited it: https://bearddesign.s-ul.eu/5em5mBg6.png

So, this issue was closed because I am not adding back the notification dot(or at least until BetterDiscord allows settings). I understand how listening to the community of users who use my theme can be a good thing, which is why I have a feedback page that I try to promote as much as possible without being too aggressive. 

I won't do a strawpoll because:
1. That website is really easy to trick and bot answers.
2. The only way I would be able to make people aware of it would be through the only place I allow myself to put a message in, the theme panel, as I try to not be too intrusive. But the problem with that is that it would greatly encourage a vocal minority to choose what they want instead of the silent majority. As of now there is only a few people (5-10) that have made it clear to me that this is an issue.

For a point of comparison, when I changed to circles, the people complaining to me about the **color** of the circle were in the hundreds.

I will probably add it as a setting when BD v2.0 comes out with theme settings.

As for the copyright stuff, I know that I don't actually have any legal rights on my code, but I don't want to encourage people to post their versions of it online. I worked hard to get my theme to where it is now (both on quality and popularity) and it would make me sad to see someone steal my code, edit it slightly and claim it as their own or don't credit me properly. And that's not really even a credit issue, but more of a moral issue. I'm not gonna extend any more on this subject but I hope you get it.

**Comment by KuroThing** [comment]
Thank you for your response and plans in regards to this issue, @BeardDesign1. I'm a bit sad that it took someone being so aggressive then editing their message for you to respond, but at least anyone who comes across this issue can now see what you're planning to do, and not the silent treatment.
